name: Build & Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew testDebug

      - name: Assemble
        env:
          VERSION_CODE: ${{ github.run_number }}
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  pre-release-upload:
    needs: build
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/pre-release-upload.yml