name: Pre-Release Upload

on:
  workflow_call:

jobs:
  device-tests:
    uses: ./.github/workflows/device-tests.yml
    secrets: inherit

  pre-release-upload:
    needs: device-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_RELEASE_KEYSTORE: ${{ secrets.ENCODED_RELEASE_KEYSTORE }}
        run: echo $ENCODED_RELEASE_KEYSTORE | base64 -d > keystore

      - name: Build & Assemble Release APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase Service Account JSON
        run: echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE_64 }} | base64 -d > service_account.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
        run: firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "internal"

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CREDENTIALS }}
          packageName: com.willowtree.vocable
          releaseFiles: app/build/outputs/apk/release/app-release.apk
          track: alpha